name: GitLab URIIT Sync

on: [push]

jobs:
  sync:
    name: GitLab URIIT Sync
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: action-pack/gitlab-sync@v3
        with:
          username: ${{ secrets.GITLAB_USERNAME }}
          url: https://gitlab.hackathon.uriit.ru/${{ github.repository }}.git
          # Personal access token from gitlab.com 
          token: ${{ secrets.GITLAB_TOKEN }}
