name: GitLab URIIT Sync

on: [push]

jobs:
  sync:
    name: GitLab URIIT Sync
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: net-engine/github-repository-sync-action@v1
        with:
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          target_repo_url: git@gitlab.hackathon.uriit.ru:2224/SOLUTIONS/test.git
